# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- prod

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build
  displayName: 'Integration Angular App'

# - task: AzureRmWebAppDeployment@4
#   inputs:
#     ConnectionType: 'AzureRM'
#     azureSubscription: 'Suscripci贸n de Azure 1(51a516f5-dd68-492a-94e9-0fc57d66dd73)'
#     appType: 'webApp'
#     WebAppName: 'ultra-group-hotel-test-front'
#     packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
#   displayName: 'Deploy on App Service'

#Copy Files to: $(Build.ArtifactStagingDirectory)
# - task: CopyFiles@2
#   displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
#   inputs:
#     SourceFolder: '$(System.DefaultWorkingDirectory)'
#     Contents: 'dist/**'
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'

#Publish Artifact: Artifact Dashboard (build)
# - task: PublishBuildArtifacts@1
#   displayName: 'Publish Artifact: Artifact Dashboard (build)'
#   inputs:
#     #PathtoPublish: '$(Parameters.ArtifactStagingDirectory)'
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'Artifact Dashboard (build)'

# - task: AzureRmWebAppDeployment@4
#   displayName: 'Deploy Web App'
#   inputs:
#     azureSubscription: 'Suscripci贸n de Azure 1(51a516f5-dd68-492a-94e9-0fc57d66dd73)'
#     WebAppName: 'webApp'
#     deployToSlotOrASE: true
#     ResourceGroupName: GroupName
#     SlotName: dev
#     package: '$(System.DefaultWorkingDirectory)/Artifact Dashboard (build staging)/Artifact Dashboard (build)/dist'

# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: 'Suscripci贸n de Azure 1(51a516f5-dd68-492a-94e9-0fc57d66dd73)'
#     appType: 'webApp'
#     appName: 'ultra-group-hotel-test-front'
#     #package: '$(System.DefaultWorkingDirectory)/**/*.zip'
#     package: $(Pipeline.Workspace)/a/angular-web-app
#     deploymentMethod: 'auto'
#   displayName: 'Deploy Web App'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Suscripci贸n de Azure 1(51a516f5-dd68-492a-94e9-0fc57d66dd73)'
    appType: 'webApp'
    appName: 'ultra-group-hotel-test-front-node'
    package: '$(System.DefaultWorkingDirectory)/dist/*'
    deploymentMethod: 'auto'